TicketSystem/TicketSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('tickets.urls', namespace='tickets')),
    path('summernote/', include('django_summernote.urls')),


]


if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    if settings.STATIC_ROOT:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TicketSystem/tickets/urls.py
from django.urls import path

from . import views

app_name = 'tickets'

urlpatterns = [
    path('', views.main, name='main'),
    path('list/', views.ticket_list, name='list'),
    path('detail/<int:pk>/add', views.add_file_to_ticket, name='add_file'),
    path('detail/<int:id>/', views.ticket_detail, name='detail'),
    path('delete/<int:id>/', views.delete_view, name='delete'),
    path('create/', views.create_ticket, name='create'),
]

TicketSystem/tickets/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
import datetime

class Product(models.Model):
    title = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='logo/products')

    def __str__(self):
        return self.title

TICKET_STATUS_CHOICES = [
    ('New', 'New'),
    ('Troubleshooting', 'Troubleshooting'),
    ('Closed', 'Closed')
]

class File(models.Model):
    ticket = models.ForeignKey('Ticket', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True, default='File')
    file = models.FileField(upload_to='files/%Y/%m/%d', blank=True, null=True)

    def __str__(self):
        return self.name

class Ticket(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    subject = models.CharField(max_length=200)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=TICKET_STATUS_CHOICES, default='New')
    responsible_user = models.ForeignKey(User,related_name='Responsible', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse("tickets:detail", kwargs={"id": self.pk})

class TicketComment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    posted = models.BooleanField(default=True)

    def __str__(self):
        return 'User {} commented  in {}'.format(self.creator, self.ticket)

TicketSystem/tickets/forms.py
from django import forms
from django_summernote.widgets import  SummernoteWidgetBase, SummernoteWidget

from .models import Ticket, File, TicketComment


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['product', 'subject', 'text']


class TicketChangingStatusForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['status', 'responsible_user']
        widgets = {'status': forms.HiddenInput(),
                   'responsible_user': forms.HiddenInput()}



class AddFileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['file']
        #Add file extns checking


#Comment Form
'''
Completed. Need IMPORT MODEL'''


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = TicketComment
        fields = ['message']

TicketSystem/tickets/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, reverse
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Ticket, TicketComment, File, Product
from .forms import TicketForm, AddFileForm, AddCommentForm, TicketChangingStatusForm

'''
Rebuild to CLASS BASED VIEWS !IMPORTANT 
'''


@login_required
def main(request):
    last_five_tickets = Ticket.objects.all()[:6]
    #Dashboard of three cases status N/TB/C
    ticket_new = Ticket.objects.filter(status='New').count()
    ticket_tb = Ticket.objects.filter(status='Troubleshooting').count()
    ticket_closed = Ticket.objects.filter(status='Closed').count()
    admin_ticket = Ticket.objects.all()

    return render(request, 'tickets/main.html', {'last_five_tickets' : last_five_tickets,
                                                 'ticket_new': ticket_new,
                                                 'ticket_tb': ticket_tb,
                                                 'ticket_closed': ticket_closed,
                                                 'admin_ticket': admin_ticket})


''' Ticket list view function | permission settings'''


@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(creator=request.user)
    ticket_admin = Ticket.objects.all()
    return render(request, 'tickets/list.html', {'tickets': tickets,
                                                 'ticket_admin': ticket_admin,})


'''Ticket detail view function, adding comment, adding file, changing ticket status'''


@login_required
def ticket_detail(request, id):
    ticket = get_object_or_404(Ticket, id=id)
    files = File.objects.filter(ticket=ticket)
    form = AddCommentForm()
    form_status = TicketChangingStatusForm(request.POST or None, instance=ticket)
    comment = TicketComment(creator=request.user, ticket=ticket)
    comments = TicketComment.objects.filter(ticket=ticket)

    if request.method == 'POST':
        if form_status.is_valid():
            #Change status form-button
            form_status.save(commit=False)
            if ticket.status == 'New':
                user = User.objects.get(id=request.user.pk)
                ticket.responsible_user = user
                ticket.status = 'Troubleshooting'
            elif ticket.status == 'Troubleshooting':
                ticket.status = 'Closed'
            form_status.save()
            #Add comment form
        form = AddCommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            subject = 'New comment in ticket #{}'.format(ticket.pk)
            message = 'You have new message from {}:\n' \
                      '{}'.format(comment.creator, comment.message)
            from_smtp = 'smtpserverffff@gmail.com'
            to = ['jojopanda8093@gmail.com', ticket.creator.email]
            send_mail(subject, message, from_smtp, to)
            #Adding sendmail to admin and to creator of comment
        return HttpResponseRedirect(reverse('tickets:detail', args=[ticket.pk]))
    else:
        form = AddCommentForm()
        context = {'form': form, 'ticket': ticket,
                   'files': files, 'comments': comments,
                   'form_status': form_status}
        return render(request, 'tickets/detail.html', context)


'''Create ticket view function, email sending'''


@login_required
def create_ticket(request):
    ticket = Ticket(creator=request.user)

    if request.method == 'POST':
        form = TicketForm(request.POST or None, instance=ticket)
        if form.is_valid():
            form.save()
            '''Sending mail to admin about creating ticket'''
            subject = request.POST['subject']
            message = request.POST['text']
            from_smtp = 'smtpserverfffff@gmail.com'
            to = ['jojopanda8093@gmail.com']
            send_mail(subject, message, from_smtp, to)

            return HttpResponseRedirect(reverse('tickets:detail', args=[ticket.pk]))
    else:
        form = TicketForm()
        return render(request, 'tickets/create.html', {'form': form,})


'''
Checking files extension
'''


''' Adding files to existing tickets'''


@login_required
def add_file_to_ticket(request, pk):
    ticket = get_object_or_404(Ticket, id=pk)
    form = AddFileForm()

    if request.method == 'POST':
        file = File(ticket=ticket, name=request.FILES['file'])
        form = AddFileForm(request.POST, request.FILES, instance=file)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('tickets:detail', args=[ticket.pk]))
    else:
        form = AddFileForm()
        return render(request, 'tickets/add.html', {'form': form})


''' Deleting ticket view function '''


@login_required
def delete_view(request, id):
    ticket = get_object_or_404(Ticket, id=id)

    if request.method == 'POST':
        ticket.delete()
        return HttpResponseRedirect(reverse('tickets:list'))
    return render(request, 'tickets/delete.html', {})

TicketSystem/tickets/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}Ticket System{% endblock %}
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <div class="wrapper ">
        <!-- Sidebar Holder -->
        <nav id="sidebar" >
            <div class="sidebar-header ">
                <h3>Ticket System</h3>
            </div>
            <ul class="list-unstyled components">
                {% if user.is_staff %}
                <li>
                    <a href="{% url 'tickets:main' %}" >Home</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'tickets:list' %}" >Cases</a>
                </li>
                <li>
                    <a href="#">Profile(Soon)</a>
                </li>
                {% if user.is_staff %}
                <li>
                    <a href="#">Knowledge Base(soon)</a>
                </li>
                {% endif %}
            </ul>
            <ul class="list-unstyled CTAs">
             {% if user.is_staff %}
                <li>
                    <a href="{% url 'user_creation'%}" class="download">Create User</a>
                </li>
             {% endif %}
            </ul>
        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="navbar-btn">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">
                                    <img src="{% static 'img/logout.png' %}" alt="logout">
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            {% block content%}
            {% endblock %}
        </div>
    </div>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
    </script>
</body>

</html>