TicketSystem/TicketSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('tickets.urls', namespace='tickets')),
    path('summernote/', include('django_summernote.urls')),


]


if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    if settings.STATIC_ROOT:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TicketSystem/tickets/urls.py
from django.urls import path

from . import views

app_name = 'tickets'

urlpatterns = [
    path('', views.main, name='main'),
    path('list/', views.ticket_list, name='list'),
    path('detail/<int:pk>/add', views.add_file_to_ticket, name='add_file'),
    path('detail/<int:id>/', views.ticket_detail, name='detail'),
    path('delete/<int:id>/', views.delete_view, name='delete'),
    path('create/', views.create_ticket, name='create'),
]

TicketSystem/tickets/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
import datetime

class Product(models.Model):
    title = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='logo/products')

    def __str__(self):
        return self.title

TICKET_STATUS_CHOICES = [
    ('New', 'New'),
    ('Troubleshooting', 'Troubleshooting'),
    ('Closed', 'Closed')
]

class File(models.Model):
    ticket = models.ForeignKey('Ticket', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True, default='File')
    file = models.FileField(upload_to='files/%Y/%m/%d', blank=True, null=True)

    def __str__(self):
        return self.name

class Ticket(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    subject = models.CharField(max_length=200)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=TICKET_STATUS_CHOICES, default='New')
    responsible_user = models.ForeignKey(User,related_name='Responsible', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse("tickets:detail", kwargs={"id": self.pk})

class TicketComment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    posted = models.BooleanField(default=True)

    def __str__(self):
        return 'User {} commented  in {}'.format(self.creator, self.ticket)

TicketSystem/tickets/forms.py
from django import forms
from django_summernote.widgets import  SummernoteWidgetBase, SummernoteWidget

from .models import Ticket, File, TicketComment


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['product', 'subject', 'text']


class TicketChangingStatusForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['status', 'responsible_user']
        widgets = {'status': forms.HiddenInput(),
                   'responsible_user': forms.HiddenInput()}



class AddFileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['file']
        #Add file extns checking


#Comment Form
'''
Completed. Need IMPORT MODEL'''


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = TicketComment
        fields = ['message']

TicketSystem/tickets/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, reverse
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Ticket, TicketComment, File, Product
from .forms import TicketForm, AddFileForm, AddCommentForm, TicketChangingStatusForm

'''
Rebuild to CLASS BASED VIEWS !IMPORTANT 
'''


@login_required
def main(request):
    last_five_tickets = Ticket.objects.all()[:6]
    #Dashboard of three cases status N/TB/C
    ticket_new = Ticket.objects.filter(status='New').count()
    ticket_tb = Ticket.objects.filter(status='Troubleshooting').count()
    ticket_closed = Ticket.objects.filter(status='Closed').count()
    admin_ticket = Ticket.objects.all()

    return render(request, 'tickets/main.html', {'last_five_tickets' : last_five_tickets,
                                                 'ticket_new': ticket_new,
                                                 'ticket_tb': ticket_tb,
                                                 'ticket_closed': ticket_closed,
                                                 'admin_ticket': admin_ticket})


''' Ticket list view function | permission settings'''


@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(creator=request.user)
    ticket_admin = Ticket.objects.all()
    return render(request, 'tickets/list.html', {'tickets': tickets,
                                                 'ticket_admin': ticket_admin,})


'''Ticket detail view function, adding comment, adding file, changing ticket status'''


@login_required
def ticket_detail(request, id):
    ticket = get_object_or_404(Ticket, id=id)
    files = File.objects.filter(ticket=ticket)
    form = AddCommentForm()
    form_status = TicketChangingStatusForm(request.POST or None, instance=ticket)
    comment = TicketComment(creator=request.user, ticket=ticket)
    comments = TicketComment.objects.filter(ticket=ticket)

    if request.method == 'POST':
        if form_status.is_valid():
            #Change status form-button
            form_status.save(commit=False)
            if ticket.status == 'New':
                user = User.objects.get(id=request.user.pk)
                ticket.responsible_user = user
                ticket.status = 'Troubleshooting'
            elif ticket.status == 'Troubleshooting':
                ticket.status = 'Closed'
            form_status.save()
            #Add comment form
        form = AddCommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            subject = 'New comment in ticket #{}'.format(ticket.pk)
            message = 'You have new message from {}:\n' \
                      '{}'.format(comment.creator, comment.message)
            from_smtp = 'smtpserverffff@gmail.com'
            to = ['jojopanda8093@gmail.com', ticket.creator.email]
            send_mail(subject, message, from_smtp, to)
            #Adding sendmail to admin and to creator of comment
        return HttpResponseRedirect(reverse('tickets:detail', args=[ticket.pk]))
    else:
        form = AddCommentForm()
        context = {'form': form, 'ticket': ticket,
                   'files': files, 'comments': comments,
                   'form_status': form_status}
        return render(request, 'tickets/detail.html', context)


'''Create ticket view function, email sending'''


@login_required
def create_ticket(request):
    ticket = Ticket(creator=request.user)

    if request.method == 'POST':
        form = TicketForm(request.POST or None, instance=ticket)
        if form.is_valid():
            form.save()
            '''Sending mail to admin about creating ticket'''
            subject = request.POST['subject']
            message = request.POST['text']
            from_smtp = 'smtpserverfffff@gmail.com'
            to = ['jojopanda8093@gmail.com']
            send_mail(subject, message, from_smtp, to)

            return HttpResponseRedirect(reverse('tickets:detail', args=[ticket.pk]))
    else:
        form = TicketForm()
        return render(request, 'tickets/create.html', {'form': form,})


'''
Checking files extension
'''


''' Adding files to existing tickets'''


@login_required
def add_file_to_ticket(request, pk):
    ticket = get_object_or_404(Ticket, id=pk)
    form = AddFileForm()

    if request.method == 'POST':
        file = File(ticket=ticket, name=request.FILES['file'])
        form = AddFileForm(request.POST, request.FILES, instance=file)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('tickets:detail', args=[ticket.pk]))
    else:
        form = AddFileForm()
        return render(request, 'tickets/add.html', {'form': form})


''' Deleting ticket view function '''


@login_required
def delete_view(request, id):
    ticket = get_object_or_404(Ticket, id=id)

    if request.method == 'POST':
        ticket.delete()
        return HttpResponseRedirect(reverse('tickets:list'))
    return render(request, 'tickets/delete.html', {})

TicketSystem/tickets/templates/tickets/add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block title %}<title>Add file</title> {% endblock%}

{% block content %}



<div class="container">
    <p>You can upload files for detail investigation your case</p>
    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-danger">Add file</button>

</form>
    </div>
{% endblock %}

TicketSystem/tickets/templates/tickets/create.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
 {% block title %}<title>Ticket System</title> {% endblock%}

{% block content %}
<form  method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-info">Create</button>
</form>


{% endblock %}

TicketSystem/tickets/templates/tickets/delete.html
{% load static %}


{% block content %} 
<form method="POST">
{% csrf_token %}
Are you sure?
<input type='submit', value='Yes'>
</form>

{% endblock %}

TicketSystem/tickets/templates/tickets/detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}<title>{{ ticket.subject }}</title>{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h2>{{ ticket.subject }}</h2>

<p>{{ ticket.text }}</p>
<span
        {% if ticket.status == 'New' %}
        class="badge badge-pill badge-danger mt-3 mb-3">
        {% elif ticket.status == 'Troubleshooting' %}
        class="badge badge-pill badge-warning mt-3 mb-3">
        {% else %}
        class="badge badge-pill badge-success mt-3 mb-3">
        {% endif %}
        {{ ticket.status }}
</span>
                {% if user.is_authenticated and user.is_staff %}
        <form  method="post">
        {% csrf_token %}
        {{ form_status }}
     {% if ticket.status == 'New' %}
            <button class="btn btn-info mt-3 mb-3">Take to work</button>
     {% elif ticket.status == 'Troubleshooting' %}
            <button class="btn btn-success mt-3 mb-3">Close Case</button>
     {% endif %}
        </form>
        {% endif %}


</div>
    <div class="col-md-6"><p> Ticket create by: {{ ticket.creator }}</p>
        {% if ticket.status != "Closed" %}

        <small>You can upload files for additional information</small>
        <br>
    <a href="{% url 'tickets:add_file' ticket.pk %}"><button type="submit" class="btn btn-danger">Add</button></a>
        <br>
        <br>
        <br>
        {% if files %}
        <small>Uploaded files: </small>
        <br>
        {% endif %}
        {% for file in files %}

    <a class='mt-3' href="{{file.file.url}}">- {{file}}</a>
        <br>
    {% endfor %}
        {% endif %}
    </div>

</div>

<h2>Discussion</h2>
{% for comment in comments %}
<div class="jumbotron">
  <div class="container">
    <h6>User: {{comment.creator}}</h6>
    <p class="" style="color: #000000">Message: {{comment.message}}</p>
      <small>Created: {{comment.created}}</small>
  </div>
</div>
{% endfor %}

{% if ticket.status != 'Closed' %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form%}
    <button class="btn btn-success" type="submit">Comment</button>
</form>
{% endif %}
{% endblock %}

TicketSystem/tickets/templates/tickets/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}<title>Tickets</title>{% endblock%}

{% block content %}
{% if not user.is_staff %}
<a href="{% url 'tickets:create' %}"><button class="btn btn-info">Create New Case</button></a>
{% endif %}

<div class="line"></div>
<div class="row">
    {% if not user.is_staff %}
{% for ticket in tickets %}
<div class="col-md-4">
<div class="card mb-3 ml-4" style="width: 18rem;">
  <div class="card-body">
      <a href="{% url 'tickets:detail' ticket.pk %}"> <h5 class="card-title">Ticket number #{{ ticket.id }}</h5></a>
    <p class="card-subtitle mb-2 text-muted">{{ ticket.subject }}</p>
    <p class="card-text"> {{ ticket.text|slice:":20"}}</p>
<div class="row">
      <div class="col-md-6"> <a href="{% url 'tickets:detail' ticket.pk %}" class="card-link">Detail</a> </div>

      <div class="col-md-6">
          <span
                  {% if ticket.status == 'New'%}
                       class="badge badge-pill badge-danger">
                  {% elif ticket.status == 'Troubleshooting' %}
                       class="badge badge-pill badge-warning">
                  {% else %}
                       class="badge badge-pill badge-success">
                  {% endif %}
              {{ ticket.status }}
          </span>
      </div>
</div>
       </div>
</div>
</div>
{% endfor %}
      {% else %}
      {% for ticket in ticket_admin %}
<div class="col-md-4 mb-4">
<div class="card m-auto" style="width: 18rem;">
  <div class="card-body m-auto">
      <div class="row">
          <div class="col-md-10">
              <a href="{% url 'tickets:detail' ticket.pk %}">
                  <h5 class="card-title">Ticket number #{{ ticket.id }}</h5>
              </a>
          </div>
          <div class="col-md-2">
              <a href="{% url 'tickets:delete' ticket.pk %}">
                  <img src="{% static 'img/cancel.png' %}" alt="Delete" width="15px">
              </a>
          </div>

      </div>



    <h6 class="card-subtitle">{{ ticket.subject }}</h6>

      <small>Product: {{ ticket.product }}</small>
      <br>
      <small>Created: {{ ticket.created }} </small>
      <br>
      <small>User: {{ ticket.creator }}</small>
      <hr>

<div class="row">
      <div class="col-md-6"> <a href="{% url 'tickets:detail' ticket.pk %}" class="card-link">Detail</a> </div>

      <div class="col-md-6">
          <span
                  {% if ticket.status == 'New'%}
                       class="badge badge-pill badge-danger">
                  {% elif ticket.status == 'Troubleshooting' %}
                       class="badge badge-pill badge-warning">
                  {% else %}
                       class="badge badge-pill badge-success">
                  {% endif %}
              {{ ticket.status }}
          </span>
      </div>
</div>
       </div>
</div>
</div>
{% endfor %}
      {% endif %}


</div>
{% endblock %}

TicketSystem/tickets/templates/tickets/main.html
{% extends 'base.html' %}
{% load static %}

{% load bootstrap4 %}

{% block title %}<title> TS - Main</title> {% endblock %}


{% block content %}
{% if not user.is_staff %}
<a href="{% url 'tickets:create' %}"><button class="btn btn-info">Create New Case</button></a>
{% endif %}

{% if user.is_staff %}
<h1>Tickets</h1>
  <hr>
<div class="row">

  <div class="col-md-4 mb-4">
    <div class="card text-white bg-danger m-auto" style="max-width: 18rem;">
  <div class="card-header text-center">New</div>
  <div class="card-body m-auto">

    <h1 class="card-text text-center">{{ticket_new}}</h1>
  </div>
  </div>
  </div>
  <div class="col-md-4 mb-4">
     <div class="card text-white bg-warning m-auto" style="max-width: 18rem;">
  <div class="card-header text-center">Troubleshooting</div>
  <div class="card-body m-auto">
    <h1 class="card-text text-center">{{ticket_tb}}</h1>

  </div>
     </div>
  </div>
  <div class="col-md-4 mb-4">
      <div class="card text-white bg-success m-auto" style="max-width: 18rem;">
  <div class="card-header text-center">Closed</div>
  <div class="card-body m-auto">

    <h1 class="card-text text-center">{{ticket_closed}}</h1>
  </div>
    </div>
  </div>

</div>
{% endif %}

{% if user.is_staff%}
<h2>Latest cases</h2>
<hr>
<div class="row">
{% for ticket in last_five_tickets %}

<div class="col-md-4 mb-4">
<div class="card m-auto" style="width: 18rem;">
  <div class="card-body m-auto">
      <div class="row">
          <div class="col-md-10">
              <a href="{% url 'tickets:detail' ticket.pk %}">
                  <h5 class="card-title">Ticket number #{{ ticket.id }}</h5>
              </a>
          </div>
          <div class="col-md-2">
              <a href="{% url 'tickets:delete' ticket.pk %}">
                  <img src="{% static 'img/cancel.png' %}" alt="Delete" width="15px">
              </a>
          </div>

      </div>



    <h6 class="card-subtitle">{{ ticket.subject }}</h6>
      <small>Product: {{ ticket.product }} </small>
      <br>
      <small>Created: {{ ticket.created }} </small>
      <br>
      <small>User: {{ ticket.creator }}</small>
      <hr>

<div class="row">
      <div class="col-md-6"> <a href="{% url 'tickets:detail' ticket.pk %}" class="card-link">Detail</a> </div>

      <div class="col-md-6">
          <span
                  {% if ticket.status == 'New'%}
                       class="badge badge-pill badge-danger">
                  {% elif ticket.status == 'Troubleshooting' %}
                       class="badge badge-pill badge-warning">
                  {% else %}
                       class="badge badge-pill badge-success">
                  {% endif %}
              {{ ticket.status }}
          </span>
      </div>
</div>
       </div>
</div>
</div>

{% endfor %}
</div>

{% endif %}

      {% endblock %}